kind: Pod
apiVersion: v1
metadata:
  name: testpod3

spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo hello-sai; sleep 200 ; done"]

    - name: c01
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo hello-manish; sleep 200 ; done"]
