apiVersion: apps/v1
kind: Deployment

metadata:
  name: efspvdeploy

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mypv

  template:
    metadata:
      labels:
        app: mypv

    spec:
      containers:
        - name: c01
          image: ubuntu
          command:
            ["/bin/bash", "-c", "while true; do echo 'Container is Running'; sleep 2000; done"]

          volumeMounts:
            - name: myvolume
              mountPath: "/tmp/contvol"

      volumes:
        - name: myvolume
          persistentVolumeClaim:
            claimName: myefsvolclaim

